name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    # 关键修改1：添加最小权限声明
    permissions:
      contents: write  # 用于推送gh-pages分支
      issues: write    # 允许操作Issues（创建/修改心愿）
      pull-requests: write  # 兼容部分API操作
      
    steps:
      - uses: actions/checkout@v3
        with:
          # 关键修改2：启用持久化认证
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install Dependencies
        working-directory: ./client
        run: npm ci
          
      - name: Build Project
        working-directory: ./client
        run: npm run build
        env:
          # 关键修改3：使用GitHub Actions自动生成的Token
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 替代自定义Token
          # 关键修改4：传递必要参数
          VITE_REPO_OWNER: ${{ github.repository_owner }}
          VITE_REPO_NAME: ${{ github.event.repository.name }}
          
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # 关键修改5：使用系统Token
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist