name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 部署需要
      issues: write    # 操作Issues需要
      pull-requests: write
      actions: read    # 允许访问Actions信息
      
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install Dependencies
        working-directory: ./client
        run: npm ci
          
      - name: Build Project
        working-directory: ./client
        run: npm run build
        env:
          # 安全传递环境变量（不会暴露到客户端代码）
          VITE_API_URL: ${{ secrets.API_URL }}
          VITE_REPO_OWNER: ${{ github.repository_owner }}
          VITE_REPO_NAME: ${{ github.event.repository.name }}

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist