name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install Dependencies
        working-directory: ./client
        run: npm ci
          
      - name: Build Project
        working-directory: ./client
        run: npm run build
        env:
          VITE_GH_TOKEN: ${{ secrets.GH_TOKEN }}
          VITE_REPO_OWNER: ${{ github.repository_owner }}
          VITE_REPO_NAME: ${{ github.event.repository.name }}
          
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist